apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-oidc
  namespace: oauth2-proxy
type: Opaque
stringData:
  client-id: oauth2-proxy
  client-secret: CXSscHv8aKYZopAs6zEb5aTq6Fc6Ezzp
  cookie-secret: Gnb0NgLoPc/XXjfoPPA1QRY4mITk63Tt
