apiVersion: v1
kind: Secret
metadata:
    name: nats-auth
    namespace: database
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:cueSX20=,iv:S6/495e5ma6P/cT9WFOIkbcIkzOeHv3qa2BBdrPRTv0=,tag:StoHYC6Nqc3mDxZYQxM6lw==,type:str]
    password: ENC[AES256_GCM,data:rC2SxaPoN30UoVrmoJy0iPRscg==,iv:2gjlSdI9QhXROQZV+OLaPQKklJOIwtnQjgVvBZMehx8=,tag:NbCAqgF1tEZTJmMcXk0Iyg==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUE52S2VqYndSQnY2SHBM
            dFlVTEUzeGpqamdSTTVFb1BpTkR3WlMwUTN3Cm44SXFQRWE5L0NOWlVGeTMzNTF5
            enNSWjNjcThQNzZmTE1CNklub1VxV2sKLS0tIExqcm1VWDJyTXBZOXJQdXI2b3Ay
            WGVZWmkvRDNVUHBUbzhlMDBtZmlZTUEKLexYZpXE0qNTMz1y7XjBOp9pO13LHLAC
            oXY4A2vAO4DQ90bx7nhHLDiaUBPQlLAgZApVo+rPUIKUi5z1oiPm3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T15:13:59Z"
    mac: ENC[AES256_GCM,data:7P0kt0NcZWuWJejI5d63GH94g5GCcpW2l4FEYchAyoRWhQ70vDrm9mokgSI7YVj+N1EaBPaYFFab/702zn2WghhNSqEOtjfqNiZRE6C3YJ4LoQOoinopV3Cn8JR2UZGkCbzgaY3D2Bz9gm1CvZOzgNZysyBht02v0kCIjf6qbj0=,iv:hqBYV60mIpp2mlW23AS4+5loXStT7nu5feBiLfCgLsI=,tag:yC//bRJYxJMItnrbQEYS+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
