apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:tnqzT6M=,iv:lJ9jy0TiV2HMFrDaXuQgg1BXXyLENmBfeTBuwpmPF3Y=,tag:GpLqKU1ImcUa9J4XRFDFmA==,type:str]
    admin-password: ENC[AES256_GCM,data:wh+J7HH09M673fdg88zszNdDbA==,iv:mRiTn4NK+DSJ1IpSeEHnNHpUbjjzSfBHkhv7f4IoENg=,tag:21EMSFC64vUVKdkcKvwK/g==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQUk0TmdMM09yMGgrM2hN
            dFQvaFl3VkJzMFU1OUFYUjZpWVkrZElKM3hrCllQdXdidVRmdi9CZHBFbGNud1V3
            MmVyalFWeFA1bm1qc2VYT0tRMkc1KzgKLS0tIDlTak1KYVo4aXBudC9pUU4rRlVS
            RjIvb3Q5ckxYRGNnMlV4OUpiajR6M2sKMwUh7059NLR/bo1O1hjGQE/5dI0KXoCT
            5+Q5ek5blu80yeuSa6m/38yhlP0iM08mvKcXOr4pHMGf+YKgE6u8tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T07:13:48Z"
    mac: ENC[AES256_GCM,data:7RnGgxnjacpG0+CXkIvaC5XIB/W/P58rUfXCLSFNHV4ir48vpxatuUDKtkWsnl7ag1sJMlQ5szGSKUg0E/U7kfshKlQqmp7r9PLalq912cr+pkz6tnVKIDPo7MjjcqaNqtp0ERTTUp8FWO/eUuqT+Vwv5f3DSV/yIKqYgkW3GIM=,iv:SRcC6m5/LG3IB+fKxWteTmFGSV/rU10TFvhY4grb8So=,tag:vh0x+MH1+9fbezt/M6GsJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
