apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc-secret
    namespace: monitoring
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Bfeghy+PHnv7aoaslmQsRKZ9ze5PUT6WlBv3rvunqPo=,iv:EAW5LWcGEAfr5D9qsaIAbeQkV0xgHYmgeyICGRysr0M=,tag:wovA79ZZuUk8XeGa95S75A==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTW5Yd2dPd1pVbVhIR25Q
            MnRjYTdXQnlEU0RxZWxOOVBWdWEwM25QRkFjClhTMHNXKzBUTVk5VGowYXZOaEVD
            NnQ1ZnNBMzVqbzZoaVp2YUl1MXhONmcKLS0tIFk3Tzh6STZJR0MzVkgxaGgvT2Vu
            U3pNeUxEODMzMXI1MmRTbE01dy9UKzQKjxMQydzw3G6yAmgVQaehhz4Durc6z72O
            gpEl9F6Uz9+3ReOgKxjGNartedvnDig9J9YXY9CEUU28Vgcq4ZNalQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T08:35:59Z"
    mac: ENC[AES256_GCM,data:Zak1f7Fo5WAQVjFFXXbErnpeiEz2rtHIoPJeIO+e4Sgs6Zn7nK+S6q/otGdPAsmddBt4Z4NaoJ0roycVPbbGsNTUDNhFPQ61qmOeloI8Uvqb39rmwt8Z+xsfTanetXabFAORpaxuCUUayP4Ucn4QzeIUAoh8n9UHOHS7klwV+mQ=,iv:CVYs49DXhMJNArDZSuOLlRvFsGWtMefJ6Ey9aWgMjgE=,tag:5AaXVzQ+zmGRh8z0tkj0SA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
