apiVersion: v1
kind: Secret
metadata:
    name: dragonfly-auth
    namespace: database
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:FbMkLlIKPfN0VY4z8rp1K55bww==,iv:GnwhaB7pu4RisiYX/ZGBiPF1UBrPUtxk6HZyxjKpL6s=,tag:H11+omhZaB7WW/AdNVQqOw==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaVlNbjlPUTExWkV3TUM3
            SC9jZ0thcm5lNFRIU1FtZ2x4OUpSRUhmRDAwCmNBaWxqeWVMeXhDWFgxVTh6djJo
            cjZIYjZDWHhzZzN5clVjNzBGRm9pbm8KLS0tIGlOaGg0TjJpT2hGSk5HdStqc1F3
            OGZtZUJ3WTE5c0p1NERUYXJMczZLcEkK7y1TRMi2yc6MToVWxq8lsVy8w1QNxEJS
            4yxyxR5jVFT2Yc5W3J0EAVQz2pCsSgG8WCsSFkOHIdkQOJOr84OMbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T15:13:30Z"
    mac: ENC[AES256_GCM,data:YqbTQkSs6PW8jMwvLjtqFzcn/3n+/9xXPsb3gbDySPE4osaULR67TjtPJ/31ZzBMEP30sgscWxDJe95ftFCDSMCL+xxPGJNTTxjrOa7EDLvmaI1FzI6w2uJHgdp7g48EWsuxeqVd4rhmTRdkhXDVaNSYxumAt6dtyKwmwiJt3WU=,iv:fIzXEWAdAhV7WVBSBNQu35har2xveh8BVIsPNX7XxPo=,tag:ShfTYvRYsCl03+pKFv4wDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
