all:
  children:
    homelab:
      children:
        cluster:
          children:
            master:
              hosts:
                alpha-actual:
                  ansible_host: 192.168.88.201
            worker:
              children:
                computer:
                  hosts:
                    bravo:
                      ansible_host: 192.168.88.202
                    charlie:
                      ansible_host: 192.168.88.203
                    delta:
                      ansible_host: 192.168.88.204
                object_storage:
                  hosts:
                    kilo:
                      ansible_host: 192.168.88.205
                database:
                  hosts:
                    november:
                      ansible_host: 192.168.88.206
        standalone:
          children:
            iot:
              hosts:
                mike:
                  ansible_host: 192.168.88.200
            nas:
              hosts:
                sierra:
                  ansible_host: 192.168.88.207
            builder:
              hosts:
                romeo:
                  ansible_host: 192.168.88.32
        proxy:
          hosts:
            hotel:
              ansible_host: 192.168.88.208