apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-flannel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://flannel-io.github.io/flannel
    chart: flannel
    targetRevision: "v0.28.1"
    helm:
      valuesObject:
        podCidr: "10.42.0.0/16"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-flannel
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
