apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: "1.11.0"
    helm:
      valuesObject:
        defaultSettings:
          defaultDataPath: "/var/lib/longhorn/"
          storageMinimalAvailablePercentage: "5"
          defaultReplicaCount: "2"
          allowRecurringJobWhileVolumeDetached: false
          storageReservedPercentageForDefaultDisk: 10
        ingress:
          enabled: false
        httproute:
          enabled: true
          parentRefs:
            - name: traefik
              namespace: default
          hostnames:
            - longhorn.lan
          path: /
          pathType: PathPrefix
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 2
          defaultFsType: ext4
          reclaimPolicy: Retain
          volumeBindingMode: WaitForFirstConsumer
          migratable: false
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true