- name: Reboot hosts
  hosts: all
  become: true

  tasks:
    - name: Reboot the host
      ansible.builtin.reboot:
        msg: "Reboot triggered by Ansible"
        connect_timeout: 5
        reboot_timeout: 300