apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-admin-secret
    namespace: seaweedfs
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:OJGiEF4=,iv:sk6Fi6Aw1tudrjrwN13Qc7HvPM5Xz5ieQDmgA9S9cYI=,tag:Ww1337qzWFTYeBYUCHTkAg==,type:str]
    password: ENC[AES256_GCM,data:zreKhQWXvMIatpeSX00u/g6BgWkB3rgMwOs=,iv:Yvrcp3MrorHEtuC5q67ABbUNJ75ak5YexLOLjuB9PK4=,tag:7qkdPlgawl7hxwBdsdVdEA==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYUQxSjJ0MDMxNXEvS0hY
            YWpWT0p2VEtaMXdta3psODVPdFhhcnFQTUE4CkpsMXFSdW8weUFxUVpUalV6eENV
            Y0Y5R2hxL2J1bys0U2VoR2xqajZBQ0kKLS0tIGZuZXlXZzNlWWtKNHJPWEtvQWlJ
            RStPOFVmcjQwMnYvbzB5REVMdStNdkUKG3INCza6Au0omWMgn34dTxwX/WJjvbX5
            U5HcV8uUgUt+Vu02W7EYGG4hZFVwS9DD9iCcKT5x+MRK2YDHk0CdPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T11:44:52Z"
    mac: ENC[AES256_GCM,data:muRhpm3PwnNS3FFc8iIFRStFdgW63AdrqEo9qqXjAxTueNzcS4SsDT+quXX7LVgowrszYghq/VZcA6KSgXCHBmAUYXCE7u5B7AyYkroBu2+jGTcQCP+5m2r5M9vBRMYPjM3HgaJC794Jps28jXX5wNblPgqcEjkKsxoxgMjvux0=,iv:Q6qNMKGWooIjo7P2vBGHFTD28kak5MMQLXMa2DPB+DU=,tag:HEL5QEShSMz4e5kRxcH6Gg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
