apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-admin-secret
    namespace: seaweedfs
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:eGBhcrA=,iv:+Wv49PNaBVcb6fio/z6pOij12OnBQWBpNw4J4pF2qcg=,tag:utlwICLR4bteoC2MiV92Dg==,type:str]
    password: ENC[AES256_GCM,data:oIgCT3Lstj/hmJ1XBzQj0Y/HHTIU,iv:0NYfFGHQucQhBNZwfuLMWfEflbtm6gNUOsTy5uAK+qw=,tag:PndBaiOKpGCcXTxa0aacMg==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WGJ3WjJ6eXZoY1o1TTdw
            T0F5MVRnbTJDa1FPQ1VIS0JremlmWnVNdFNZCk5TS2Z2Zk1ldkUxcmh5V1NNaGtT
            TElkZDYrcHZSRldUdEtVajdFSkJxOEkKLS0tIEdSTVlkUmtIL2cxZ3c1V0QvaHFK
            bTdMc3I2Mmd1TXhsMk1STkYzQ0FlbW8KXWBz8DQj+xfldX/Msh9UX7TmlPL+1REP
            SfU/2Id2jbA4FtCuTJu5UU9pEkldc12MMXybU4pqUYokEYRgTEwcYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T12:14:36Z"
    mac: ENC[AES256_GCM,data:uMWN7jsoEzzQMfHBqVKYOa+09keIB36L61kJRdXXUZBIUEzYP8OeQPHLbsa+MLjiEGZSU+xVrgPPbxMz8O0apI6nWPCkX0UpYxEvUoAE9JG9+QyyqqWTT7qPow7TIJ4Tkq1vd3GWdOE64qNAAfX6cxWudNb1hX1w7ovmm2xaoYo=,iv:kMHFsvvi6UvzX2fnltc0CeedR0c7koS3nTaraOnO6kk=,tag:7SkNLs/Z4Xk76ByQ8o+Gug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
