apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-admin-secret
    namespace: seaweedfs
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:CNMJMP8=,iv:1c8WeHPieLazjzmtj1eUz9kg1O5FHwsPR3lx79Zj0Fs=,tag:6Vxc0C8gZrmL4wNde5/+wA==,type:str]
    password: ENC[AES256_GCM,data:YBhPL7l7AVVpghsTDy0EpN6hBA==,iv:MvJVb7PR6fANtNmuU1/eX7kOKr8poyAcregZZEGfiHY=,tag:ijKiivzqDWRDypyx+DgcKg==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdVhnOUt6SVJmdTdYcitu
            d2t2d1dMaGcrU0E5b09SS29hcWIrd2pjZWlRCjgvNWdCbEZJZDhuZVRPeDgrRHVv
            Vm9tbXVGZFJyQ2d3UVc0WEs5NGdXK1kKLS0tIHg2WkhOSlBJbWw3NzhqeEZSL21W
            K2taRlgwWEs5VTVacWE0MUF5UEZQTGcKda7xaggisdpXD+lDj5hu+rJee0WNScEa
            G6oYz/WKNKbzdYHrRTLwgSczgcL0g/UgJPqDREBt/OUl9UtM0dqSiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T12:51:36Z"
    mac: ENC[AES256_GCM,data:HurtX4zskqtAKMTPCQbu+nwJM0Zd8CiMeUP2pMAcIu0JT5BzmxDJqW4nPDyNPL2dQeN9qL4LssobuQ3Vy+65vCBVb10gLuzlrYos2zOvyHjKPcVv/uBDkF2XexW7PPSCYS8TfPPm7qtc/+QfWOImYoSVZlVc1GtHrr98dKVzeI4=,iv:zLLnmo80HvbKwMzPAHgH/S0VTi1g/bC+jzeVnoeM78w=,tag:q5l79EanXiaLrDS6cDOOiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
