apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: seaweedfs-admin
  namespace: seaweedfs
spec:
  parentRefs:
    - name: traefik
      namespace: default
  hostnames:
    - seaweedfs-admin.lan
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: seaweedfs-admin
          port: 23646
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: seaweedfs-filer
  namespace: seaweedfs
spec:
  parentRefs:
    - name: traefik
      namespace: default
  hostnames:
    - seaweedfs.lan
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: seaweedfs-filer
          port: 8888
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: seaweedfs-s3
  namespace: seaweedfs
spec:
  parentRefs:
    - name: traefik
      namespace: default
  hostnames:
    - s3.lan
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: seaweedfs-filer
          port: 8333
