apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-auth
    namespace: seaweedfs
type: Opaque
stringData:
    seaweedfs_s3_config: ENC[AES256_GCM,data:C221IBdHZ8ly5QXGRHvVLckEeLc8TBo6Q1x6J5yj7fywRuQogh/ISEVWfpc0cz2U42vwTE1JCVZhfb4tDdcekkWI3DhyWISsnsT7bkUFIufdeGuK/s2FBjJ6DJAyhH1WuER/a5l0lvoZzsNmmk+dJ/hIISBK7wcTJ1J5aMqHLlviPEanBXH4iK7chUcV8Xer+2+UiS1hig+4yIeFlxKeeoe9TfYkbruP+3pJQr3IqCJnZQAxYUyFxAk9nT6OgwsAciNkaq7u5TYHCJh/zA3cGDwlrFJkDFerEoQWVLT6CaR566xb4wLB90T2Sa/IpxKUHa7FdfX4WWq/NK+48dKFaw==,iv:baY1fnFRtXoJ/jVDMpRqcziCjcHUYjE+QrjYVqclZb4=,tag:ugnjO27Wur1QP5lsJNsPqA==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NFFLQ0l4ZkUvcUx5NEVS
            OE5yTUExQWtTVXZDK1plYmlQeFluZFZ3WUdFCmU4T09QYmkzVCs1ZHNmQVZjY3Z4
            TjlqRFNyWGwwYWxDaHh5UXYydjBsYWcKLS0tIFJJaE5MT2ZOR2lydUo3SzZGRExE
            ZjhvWnU5dzdjZE91cC9PR2xnQXczQ2MKTJvezbB8HZhKD2VAOr8UDtY3mSisUnB/
            KU4mv5YL2bLh/9j+tf6Aj2hMAaXtuk8Bbf1Yd2hewkzBLcXyyBpnPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T16:14:33Z"
    mac: ENC[AES256_GCM,data:BXpBqASAzinJoPmZi/st9rjZow+f5CbTKQWYRkfGyMRhxf6lUIVRqJwpKsttcn7vmY8EZ8uuub35VcD3idyhOyHdupIHF4X88O4Dqtu9H1HAt97Sl7BqgJHfNKSmI1/E15eCtIevQnqZwF9gKVGHqnfcmgQJRSNbDk5WmQgcF78=,iv:q00OyocwmyBatWW+BiarRsqY5qYAsrgGSdQytll0084=,tag:0MkxeW8j9MDSbgrLrbFLfQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
