apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-auth
    namespace: seaweedfs
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:/8G2jJn3IKjC9t5AiHHDeLwormmA+B0tsBWC57RVZBH0/MfLcq6CpR2J9tcTHUOt7TSA8+D1ZBs8k5cF5BmfpheqJP4don4n5dDYTFBixl9I+nK8XaCmVeJ9B2bvqt9gkxRtXwYRyLXI98P1Z8wA7RhbhK7o8tgqPaGgQRbjMoj2WPiczjdtxBoz61Gp8SI2DbkssABkazOYz2qKlZaW/z/j7n4xr3SdPU5tzS/Pyeb4xnagZY3FfvdtfGlzb9mr1dBb9ljMQDvFvbo2wMRU8+0SiL1Ts9/t/j+LOeywL9CnaS08kOpICrOzlQYII6mZRFj1MNDvtf5zYh/31FcM8g==,iv:jsg4+QPc21NaRd5+H/mQEhRbTutLFh+IkIzxQvs1yWA=,tag:ej6Asf6LxFIRfNS0GAX5lg==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRGNVWHpOeWoxZjVQQW9V
            YkIvYUs2Ukw2b2p4T2Z5dmkvdVhzdlBnOFZ3CjlIWno3WkppNlNuUGRvZzRpUlZy
            SmtwcVFaRlZPcVFIa3dFcDJmSWIxNUUKLS0tIGhmT3hacXVWQnMzSU5BeUJ1ZjhP
            SzFOeTdVSXFVQjNhSXR2V1V1NGRtVWMK8hYpWQQLv9ga+PmGH8h7kw02c/k2BDtz
            v1pokt4s7AVg6sSrxXDirbY2mibiWIryO9IsCVEQykuyLC/hyXo/uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T15:15:44Z"
    mac: ENC[AES256_GCM,data:sZO3gEQbv3FWCURTbb6zUYW/AIrCgjEvdlIq4lm6dAQwIoxYpRHFrfRyvOSRi2clZttshIXE1kJ8GeH0bIfTMvu8QIKcPwfCvqTxALLdLGRPVZ7d5dlmvqQ6xr4xHGWPsXiDLEFcg5E2XRdeaS7Yyxz8yUb8CyozvycNAEnqlmw=,iv:cR1lWtJpoFh5fNJDTLYXurW0gLx+mPoKSGS0xUCpqu4=,tag:S2vVRBE6vEK/FnAWUjJuhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
