apiVersion: v1
kind: Secret
metadata:
    name: postgresql-admin-secret
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:2i9FPKM=,iv:O7unoz++xv4EbqLaXwlKe95o9lrqQYEGFNiZNXwXXRI=,tag:aVsmYK1mkLqVKJK+oDkDuQ==,type:str]
    password: ENC[AES256_GCM,data:8fA42Vm2aC8FNQE4YHZ9cza6gg==,iv:9jwJC+fU97Yzvpivj2hdIzODm9MAejaA++acyiPAuvQ=,tag:yT8weUuAaNLoh6Ma1yBDAg==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBna1dhSUtIRVlFSVRtMnhJ
            RkdQSVowZlVoUXRMUGZYK2tMdVdpa0VQTjJVCk1uYkRhemlJd3hmRkZpdmtBcEJt
            L1dyd0U2QmwvdVhnUHZDYlRGUlFuRzQKLS0tIEQwdldFcUFMM1pUNE0yQ2poVVpa
            dG5qdXZYMysvZ3daTHl0b25FcnV5d1UKa1J5X6pMMn0zqtvpUPELoZlOeJCycVDZ
            vUVJpSWnKNQvJSwS8tPEUsG2AnSA20CCwQlpoAFkTalei2ayqa+a0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T14:53:26Z"
    mac: ENC[AES256_GCM,data://PC9Z5Oj/W7BzQEsYbKfcUbNjTP0pWrlEg3V6IOymeQBzEAUIU3enzeGq04Sp/z4m6ihVK3gFY/ouC2QsRMr+pz1/1PYCKB0DJKOFEBrijp2LUi7LOdoUW0mXXrLNn3d1Si+HU74gJr04iJITgu0rxhiFhTbAVj2bQjkaMpo8A=,iv:A/ETCJGCVlOlNIU9s7VX9c++QInLV2UNIwykMdpSz6Y=,tag:pKAZn7PQriv7qBaxf0VMwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
