apiVersion: v1
kind: Secret
metadata:
    name: postgresql-example-secret
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:XA9HvXOb8I1uH02v,iv:A6g2IzClcKFbIPD+fDAk188kegLWKoenj3mWPqT3DNI=,tag:8odtjjudqWa1Du+HCA6Xpg==,type:str]
    password: ENC[AES256_GCM,data:xS1KqzbCM9sBk6NLRi5vrA==,iv:Wc0VjcxJEabgL6EmFR2jK7O3+5Z3kRMJU3kGcAKQTjY=,tag:6RvKDdt3oeAXtFgkIKgtdg==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQ1RQM0pNallVUHp6K2wr
            Vkhud2NJczU5cVhaYlJFUmp1dHI1YzdmNEI4Cm16Q2c5ZlJtVCtUckpORXdmYkxy
            ZDZraEgrT2Z5UDV4UEFXZmx3Y1hyWXcKLS0tIG0wZE44WThuZWZmVzVESE1NUG52
            UUxzUVFadlRFSm5RQ2lZWVpxOUpJVFUKdgWa+nkyd7PcEJPvToyUBM0hBrJrqXun
            oxzIN8mNww3krlfPSFmzmmQPQKC9GTMFPv0FeE5J/eYQ+/8aZk+7ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T12:13:12Z"
    mac: ENC[AES256_GCM,data:/iqwQxmb+KimR8L97fTFm0DU0uJQpHo/YU1KmconRkX6eJSUigyAZNGHPeKVAYbcSjnVyIdiLN9i/WMylC3sQb50loOynkZQaqKwxeebQYAF3ithA5tlUDBMYnSlCx+6fuDqFs1fWF3vsw6u78EVvcI3RF8e4SM054PfzMsf6Xk=,iv:By2SfEvapxrRdg0PU0u+LVWVTi6osc7pdxeV0JfAZro=,tag:rXpANQpY+J+mAyLZc4DXtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
