apiVersion: v1
kind: Secret
metadata:
    name: postgresql-keycloak-secret
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:H7tZw4L9ffw=,iv:sMDC2ld/4dLLSUnfIBtvYzdFtkacx3sQA7zKQC4Za/w=,tag:t7rnkzgLfRISGJDVzx7uEw==,type:str]
    password: ENC[AES256_GCM,data:iQkHsw9CZB6SvSZMJpH23zszJw==,iv:KSzolfAgK/2A9WahqIIJnkw5RhJ6lGBlSMqyxXiL4dI=,tag:1qOuxVPcMLuYMFoWNRIq8Q==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrL1pTUC92SFdReTdnUzkv
            MkZyRGFXYjB6SEw2ajhLZFM2Z1VNWlhFK1JFClBWR1Znd3pVYk5pd0RuU2dPRlpQ
            SU50NmN2anJGZ2Z3YXJsUlpQZFc2eXcKLS0tIFI4eWdHNytjQk1YY2xjcUtqUmg2
            VVlOMUtiVm9TQW84Y1FRcGpXWTlySTAKxQCNckZKmgAqU194FM+zZbdaUQ08/jIF
            00dYzyFx8mOKOOA33r53fQkZ/KD0Ue1zP6KGqcM+P9b9V9lNyYqBvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T15:43:16Z"
    mac: ENC[AES256_GCM,data:Z0PIhel3DzD4oUpTWmMpQiBzSemaw34BOCIyQpYlz1kfBnAl5gSFZFDStIsMl8R6TPr8udEZhhCEVoeIrKK4clnuNt0wAf3GdLh99lCNveFeqcuOV/IA60CHnysiMNEm8RPJj16b5wYhi9mvfoWowvKtXaRnx3fSlThk71RK85Y=,iv:jFsX1fGJY6jsfe5kk+qhMVKaJDHTJmqKtsapFJ6dQ+4=,tag:a90tYe51b6c+YIPVfEShtA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
