apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: postgresql-secret-generator
files:
  - superuser-secret.enc.yml
  - admin-secret.enc.yml
  - keycloak-secret.enc.yml
  - example-secret.enc.yml
