apiVersion: v1
kind: Secret
metadata:
    name: postgresql-superuser-secret
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:El3013cL9xQ=,iv:FK9/iSQ39Vihe3NIq7HEBc6UXVr/YWtkX9rWiGIcWyw=,tag:FHkwYOmaIu1g1z9wzy/6Og==,type:str]
    password: ENC[AES256_GCM,data:QaboBEMJARTFIZbEZ/KplK0qhw==,iv:Mwpn2KboOFsrz1E3tdQ6jUx78nCoLtPVbC4qQnuZ0U4=,tag:QeXux/0eI5+jgM1ioyk5Xw==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cFNBNXo0aDh4d0tWU2RH
            SUlIYUpYZ0kvUG1scVNiYXpNRFZjNHVKa1djCldrSWwrT01tMGJxYzNHQ0lxRGZ6
            a25DVGdnWm96SkxhazcrVy9qUElaQWMKLS0tIHJ6QjU5QVpCSk1mMG5YUC8xTkRU
            Vm1qTUs2Z3pMWmNtQVowVkphNThueHMKKAQWrgSwl4ScwHhqOG9DrUBnfPRFnmfp
            kn/osJLqTGbgYt79xRKtpGj4k4odok4TvZukIiLfeyg2JWdnYWgCAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T14:06:32Z"
    mac: ENC[AES256_GCM,data:h2VNeZMgG/ORmQLt/fEj9jbN7F56VrSB+RBIQkT+d6mVOMkv9ydMCE61oYVAKMsLEzocnnpuef6b5u+AgWU8I7enR3GTUc4MzLX2ktlS9xdMRbQTAi1+aNmEDvLrxX6tiQQqW+6TqSOHx/yONKZXld/xyBe/wc/zefRD3Si9sh8=,iv:hyYBNkTN9BbGeaSCaNUYYR4Kt1zFwIwjGOxFnctWf9k=,tag:9ermx8mIdY8fXt95mDjKpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
