apiVersion: v1
kind: Secret
metadata:
    name: zot-oidc-credentials
    namespace: zot
type: Opaque
stringData:
    oidc-credentials.json: ENC[AES256_GCM,data:5br5bEEf6aUqTkUdTm9+7XP8TPMKRTrqgMPi6z5Qjf17bSDJxY4bXeNoD0zV3oWf/MvPvkQTcJxE8hwhTyjV1cb7FNQnUAk1F0j4wTJO,iv:XGnheiKz13hoMId6b3E3LKkvaWMBpGZeWJKnt/07uXo=,tag:5F/oUVNtYKy+OZDVRt1Ipg==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuL2hlVXJ5eVprUDR5WjB5
            cG13a1hoMnltOTZ2RytLTlJKNjhMU2REQVFVCjlCWGhaSXhQSVJoK2pWb1RqTmVK
            ZDlEa2w4SXhxT1oyb3k1YWltcjNxZjAKLS0tIDcreDBEQ253WE5pWkRzdlZndXRF
            Q1I0YUFvSU1lQ0dCaTJNT1JaQmRqWk0Kj/AjWXqqurpduEwohiDiBWt5+eJ3Zc5T
            1TK8pAta7NG9S592g1ByNZiCIVd1u6msAf/Q5xLJwRJwuvWfnAVf7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T13:54:32Z"
    mac: ENC[AES256_GCM,data:fjMAOU7LDlC6NOxDqTr0/AS1xucRjpm/WK0S3jFj34aVaRk4A5hUzHtWrZl+Yiox1G/YnhFRmNQzmClJcwoJWxDpFPDsv1LuzFBgr1KjQLnAzRXosyUsBdk3wEPdG8406d6Lg/KM7Ea17S8GDee9ICcFTiZhFVrpzsEim0e96Sk=,iv:Z3eLKhe9/gxI0UR5Yg6YaD59wSmbvUZCt/el+Mfc8AE=,tag:x5WG+MMp+zFW+atWva1FIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
