apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: homelab-ca
spec:
  sources:
    - secret:
        name: homelab-ca-secret
        key: tls.crt
  target:
    configMap:
      key: homelab-ca.crt
