apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-secret
    namespace: keycloak
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:3l6+mUgeaas=,iv:62M8i4GCnaVt8kBlVoVtvURl4nKVwq7Pnm4e3R75oAE=,tag:JAee+Tkt45AU20es75pH2w==,type:str]
    password: ENC[AES256_GCM,data:5emJHirypOydK24jDjob54Ivpg==,iv:0n4Z/AyMSIc9YvAQV/wFgERVTJCAJe9oB4Agjt7h4hM=,tag:xr8+HhijOjVNSIYFmIU8qg==,type:str]
sops:
    age:
        - recipient: age1s6q3qyvmyxrxuc05ge89e94wrfvx4p2vlylas000dgz35v8cw5aqqjj62y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaEZUOGx5Z2VwRnd6ZFhG
            Z0x2VXlGeTdHUEozbXhUR0RjUTBudlVQNWpjCmZuNHZVUjVrVzdhS0ZpSTBqMDl6
            QkYvWFpoTFF3dzFkSjNkYmRhK0ZNZXcKLS0tIFJiMG1pM0hQOHBMUUUzaGJLeU1L
            TzlZS2hWTUZVUnVMUlJSZmhVWXdWb1UKH2m4J0tsAFsMYCZvQYDNtxX7ehJASD+P
            B5zMNc7tjsURoNEilPFjmgg/3TXULvxuccIlcBXcUov+Hr//mfw/Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T15:38:46Z"
    mac: ENC[AES256_GCM,data:dZtsxge7+V3D4/QfILqqM9V7eIB4F4C24lePm9yyDh2qCMCGxmLCscVngmT6n0maZvE08oHWAoDcqt6/D05HgEdA83pEdm0qsQKjqkWrr+G15S/wb0419AUQzc+32LQgwVosjsknzdJ9OE7ILAy6HzPEPz2x/dk89dWQQ2RKuCQ=,iv:r98k2xkHEWyG1U4nlFihcruj1ZWN+kSPT7nG6Edi/KA=,tag:VeEMMNapJFm9CFiYVaNd2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
