defaultSettings:
  defaultDataPath: "/var/lib/longhorn/"
  storageMinimalAvailablePercentage: "5"
  defaultReplicaCount: "2"
  allowRecurringJobWhileVolumeDetached: false
  storageReservedPercentageForDefaultDisk: 10

service:
  ui:
    type: NodePort
    nodePort: 30000

ingress:
  enabled: false

httproute:
  enabled: true
  parentRefs:
    - name: traefik
      namespace: default
  hostnames:
    - longhorn.local
  path: /
  pathType: PathPrefix

persistence:
  defaultClass: true
  defaultClassReplicaCount: 2
  defaultFsType: ext4
  reclaimPolicy: Retain
  volumeBindingMode: WaitForFirstConsumer
  migratable: false