apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-admin-nodeport
  namespace: seaweedfs
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: admin
    app.kubernetes.io/name: seaweedfs
  ports:
    - name: admin-http
      port: 23646
      targetPort: 23646
      nodePort: 30004
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-filer-nodeport
  namespace: seaweedfs
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: filer
    app.kubernetes.io/name: seaweedfs
  ports:
    - name: filer-http
      port: 8888
      targetPort: 8888
      nodePort: 30001
    - name: s3
      port: 8333
      targetPort: 8333
      nodePort: 30002